version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule: 
      interval: daily
    allow:
      - dependency-type: "production"
    # Disable version updates for npm dependencies
    open-pull-requests-limit: 0
